language: node_js
node_js: "10"

git:
  submodules: false

addons:
  apt:
    packages:
      - aspell
      - aspell-en

jobs:
  include:
    - stage: markdownlint
      script: 
      - npm install -g markdownlint-cli
      - markdownlint CHANGELOG.md
    - stage: spellcheck
      script: if [[ $(cat CHANGELOG.md | aspell --lang=en --encoding=utf-8 --personal=./.aspell.en.pws list | wc -l) -ne 0 ]]; then exit 1 ; fi
