language: node_js
node_js: "10"

addons:
  apt:
    packages:
      - aspell
      - aspell-en

install: npm install -g markdownlint-cli

jobs:
  include:
    - stage: markdownlint
      script: ./test 1
    - stage: spellcheck
      script: cat CHANGELOG.md | aspell --lang=en --encoding=utf-8 --personal=./.aspell.en.pws list