language: node_js
node_js: "10"

git:
  submodules: false

addons:
  apt:
    packages:
      - aspell
      - aspell-en

jobs:
  include:
    - stage: markdownlint
      script: 
      - npm install -g markdownlint-cli
      - markdownlint CHANGELOG.md
    - stage: spellcheck
      script: 
      - SPELLCHECK_OUT=$(cat CHANGELOG.md | aspell --lang=en --encoding=utf-8 --personal=./.aspell.en.pws list)
      - echo $SPELLCHECK_OUT
      - if [[ $(echo -n $SPELLCHECK_OUT | wc -c) -ne 0 ]]; then exit 1 ; fi
